# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/protofile.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/protofile.proto',
  package='demo',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16protos/protofile.proto\x12\x04\x64\x65mo\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\x03\"9\n\x05Value\x12\x0f\n\x07version\x18\x01 \x01(\x03\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\">\n\x08KeyValue\x12\x16\n\x03key\x18\x01 \x01(\x0b\x32\t.demo.Key\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.demo.Value\"E\n\nRequestSET\x12\x16\n\x03key\x18\x01 \x01(\x0b\x32\t.demo.Key\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"9\n\x0bResponseSET\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.demo.Value\"$\n\nRequestGET\x12\x16\n\x03key\x18\x01 \x01(\x0b\x32\t.demo.Key\"9\n\x0bResponseGET\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.demo.Value\"5\n\nRequestDEL\x12\x16\n\x03key\x18\x01 \x01(\x0b\x32\t.demo.Key\x12\x0f\n\x07version\x18\x02 \x01(\x03\"9\n\x0bResponseDEL\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.demo.Value\"F\n\x11RequestTESTANDSET\x12 \n\x08keyValue\x18\x01 \x01(\x0b\x32\x0e.demo.KeyValue\x12\x0f\n\x07version\x18\x02 \x01(\x03\"@\n\x12ResponseTESTANDSET\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.demo.Value2\xd8\x01\n\tDBService\x12,\n\x03SET\x12\x10.demo.RequestSET\x1a\x11.demo.ResponseSET\"\x00\x12,\n\x03GET\x12\x10.demo.RequestGET\x1a\x11.demo.ResponseGET\"\x00\x12,\n\x03\x44\x45L\x12\x10.demo.RequestDEL\x1a\x11.demo.ResponseDEL\"\x00\x12\x41\n\nTESTANDSET\x12\x17.demo.RequestTESTANDSET\x1a\x18.demo.ResponseTESTANDSET\"\x00\x62\x06proto3'
)




_KEY = _descriptor.Descriptor(
  name='Key',
  full_name='demo.Key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='demo.Key.key', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=50,
)


_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='demo.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='demo.Value.version', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='demo.Value.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='demo.Value.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=109,
)


_KEYVALUE = _descriptor.Descriptor(
  name='KeyValue',
  full_name='demo.KeyValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='demo.KeyValue.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='demo.KeyValue.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=173,
)


_REQUESTSET = _descriptor.Descriptor(
  name='RequestSET',
  full_name='demo.RequestSET',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='demo.RequestSET.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='demo.RequestSET.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='demo.RequestSET.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=244,
)


_RESPONSESET = _descriptor.Descriptor(
  name='ResponseSET',
  full_name='demo.ResponseSET',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='demo.ResponseSET.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='demo.ResponseSET.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=303,
)


_REQUESTGET = _descriptor.Descriptor(
  name='RequestGET',
  full_name='demo.RequestGET',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='demo.RequestGET.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=341,
)


_RESPONSEGET = _descriptor.Descriptor(
  name='ResponseGET',
  full_name='demo.ResponseGET',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='demo.ResponseGET.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='demo.ResponseGET.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=400,
)


_REQUESTDEL = _descriptor.Descriptor(
  name='RequestDEL',
  full_name='demo.RequestDEL',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='demo.RequestDEL.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='demo.RequestDEL.version', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=402,
  serialized_end=455,
)


_RESPONSEDEL = _descriptor.Descriptor(
  name='ResponseDEL',
  full_name='demo.ResponseDEL',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='de mo.ResponseDEL.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='demo.ResponseDEL.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=457,
  serialized_end=514,
)


_REQUESTTESTANDSET = _descriptor.Descriptor(
  name='RequestTESTANDSET',
  full_name='demo.RequestTESTANDSET',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keyValue', full_name='demo.RequestTESTANDSET.keyValue', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='demo.RequestTESTANDSET.version', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=516,
  serialized_end=586,
)


_RESPONSETESTANDSET = _descriptor.Descriptor(
  name='ResponseTESTANDSET',
  full_name='demo.ResponseTESTANDSET',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='demo.ResponseTESTANDSET.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='demo.ResponseTESTANDSET.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=588,
  serialized_end=652,
)

_KEYVALUE.fields_by_name['key'].message_type = _KEY
_KEYVALUE.fields_by_name['value'].message_type = _VALUE
_REQUESTSET.fields_by_name['key'].message_type = _KEY
_RESPONSESET.fields_by_name['value'].message_type = _VALUE
_REQUESTGET.fields_by_name['key'].message_type = _KEY
_RESPONSEGET.fields_by_name['value'].message_type = _VALUE
_REQUESTDEL.fields_by_name['key'].message_type = _KEY
_RESPONSEDEL.fields_by_name['value'].message_type = _VALUE
_REQUESTTESTANDSET.fields_by_name['keyValue'].message_type = _KEYVALUE
_RESPONSETESTANDSET.fields_by_name['value'].message_type = _VALUE
DESCRIPTOR.message_types_by_name['Key'] = _KEY
DESCRIPTOR.message_types_by_name['Value'] = _VALUE
DESCRIPTOR.message_types_by_name['KeyValue'] = _KEYVALUE
DESCRIPTOR.message_types_by_name['RequestSET'] = _REQUESTSET
DESCRIPTOR.message_types_by_name['ResponseSET'] = _RESPONSESET
DESCRIPTOR.message_types_by_name['RequestGET'] = _REQUESTGET
DESCRIPTOR.message_types_by_name['ResponseGET'] = _RESPONSEGET
DESCRIPTOR.message_types_by_name['RequestDEL'] = _REQUESTDEL
DESCRIPTOR.message_types_by_name['ResponseDEL'] = _RESPONSEDEL
DESCRIPTOR.message_types_by_name['RequestTESTANDSET'] = _REQUESTTESTANDSET
DESCRIPTOR.message_types_by_name['ResponseTESTANDSET'] = _RESPONSETESTANDSET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Key = _reflection.GeneratedProtocolMessageType('Key', (_message.Message,), {
  'DESCRIPTOR' : _KEY,
  '__module__' : 'protos.protofile_pb2'
  # @@protoc_insertion_point(class_scope:demo.Key)
  })
_sym_db.RegisterMessage(Key)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), {
  'DESCRIPTOR' : _VALUE,
  '__module__' : 'protos.protofile_pb2'
  # @@protoc_insertion_point(class_scope:demo.Value)
  })
_sym_db.RegisterMessage(Value)

KeyValue = _reflection.GeneratedProtocolMessageType('KeyValue', (_message.Message,), {
  'DESCRIPTOR' : _KEYVALUE,
  '__module__' : 'protos.protofile_pb2'
  # @@protoc_insertion_point(class_scope:demo.KeyValue)
  })
_sym_db.RegisterMessage(KeyValue)

RequestSET = _reflection.GeneratedProtocolMessageType('RequestSET', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTSET,
  '__module__' : 'protos.protofile_pb2'
  # @@protoc_insertion_point(class_scope:demo.RequestSET)
  })
_sym_db.RegisterMessage(RequestSET)

ResponseSET = _reflection.GeneratedProtocolMessageType('ResponseSET', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSESET,
  '__module__' : 'protos.protofile_pb2'
  # @@protoc_insertion_point(class_scope:demo.ResponseSET)
  })
_sym_db.RegisterMessage(ResponseSET)

RequestGET = _reflection.GeneratedProtocolMessageType('RequestGET', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTGET,
  '__module__' : 'protos.protofile_pb2'
  # @@protoc_insertion_point(class_scope:demo.RequestGET)
  })
_sym_db.RegisterMessage(RequestGET)

ResponseGET = _reflection.GeneratedProtocolMessageType('ResponseGET', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEGET,
  '__module__' : 'protos.protofile_pb2'
  # @@protoc_insertion_point(class_scope:demo.ResponseGET)
  })
_sym_db.RegisterMessage(ResponseGET)

RequestDEL = _reflection.GeneratedProtocolMessageType('RequestDEL', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTDEL,
  '__module__' : 'protos.protofile_pb2'
  # @@protoc_insertion_point(class_scope:demo.RequestDEL)
  })
_sym_db.RegisterMessage(RequestDEL)

ResponseDEL = _reflection.GeneratedProtocolMessageType('ResponseDEL', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEDEL,
  '__module__' : 'protos.protofile_pb2'
  # @@protoc_insertion_point(class_scope:demo.ResponseDEL)
  })
_sym_db.RegisterMessage(ResponseDEL)

RequestTESTANDSET = _reflection.GeneratedProtocolMessageType('RequestTESTANDSET', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTTESTANDSET,
  '__module__' : 'protos.protofile_pb2'
  # @@protoc_insertion_point(class_scope:demo.RequestTESTANDSET)
  })
_sym_db.RegisterMessage(RequestTESTANDSET)

ResponseTESTANDSET = _reflection.GeneratedProtocolMessageType('ResponseTESTANDSET', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSETESTANDSET,
  '__module__' : 'protos.protofile_pb2'
  # @@protoc_insertion_point(class_scope:demo.ResponseTESTANDSET)
  })
_sym_db.RegisterMessage(ResponseTESTANDSET)



_DBSERVICE = _descriptor.ServiceDescriptor(
  name='DBService',
  full_name='demo.DBService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=655,
  serialized_end=871,
  methods=[
  _descriptor.MethodDescriptor(
    name='SET',
    full_name='demo.DBService.SET',
    index=0,
    containing_service=None,
    input_type=_REQUESTSET,
    output_type=_RESPONSESET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GET',
    full_name='demo.DBService.GET',
    index=1,
    containing_service=None,
    input_type=_REQUESTGET,
    output_type=_RESPONSEGET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DEL',
    full_name='demo.DBService.DEL',
    index=2,
    containing_service=None,
    input_type=_REQUESTDEL,
    output_type=_RESPONSEDEL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TESTANDSET',
    full_name='demo.DBService.TESTANDSET',
    index=3,
    containing_service=None,
    input_type=_REQUESTTESTANDSET,
    output_type=_RESPONSETESTANDSET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DBSERVICE)

DESCRIPTOR.services_by_name['DBService'] = _DBSERVICE

# @@protoc_insertion_point(module_scope)
